'use client';

import { useState, useEffect } from 'react';
import {
  AlertOctagon,
  Zap,
  Shield,
  Clock,
  ArrowRight,
  DollarSign,
  TrendingDown,
  Users,
  ChevronRight,
} from 'lucide-react';
import { fetchApi } from '@/lib/api';

interface RecommendedAction {
  id: string;
  severity: 'Critical' | 'Optimisation' | 'Preventive';
  title: string;
  subtitle: string;
  impact: 'High' | 'Medium' | 'Low';
  customerImpact: string;
  savingsOrBenefit: string;
  effort: string;
}

interface RecommendedActionsPanelProps {
  onViewAll?: () => void;
}

export default function RecommendedActionsPanel({ onViewAll }: RecommendedActionsPanelProps) {
  const [actions, setActions] = useState<RecommendedAction[]>([]);

  useEffect(() => {
    const load = () => fetchApi<RecommendedAction[]>('/api/recommendations', []).then(setActions);
    load();
    const interval = setInterval(load, 30000);
    return () => clearInterval(interval);
  }, []);

  const severityConfig = {
    Critical: { icon: AlertOctagon, bg: 'bg-red-50', border: 'border-red-200/70', text: 'text-red-700', badge: 'bg-red-100 text-red-700 border-red-200', iconColor: 'text-red-600', dot: 'bg-red-500' },
    Optimisation: { icon: Zap, bg: 'bg-blue-50', border: 'border-blue-200/70', text: 'text-blue-700', badge: 'bg-blue-100 text-blue-700 border-blue-200', iconColor: 'text-blue-600', dot: 'bg-blue-500' },
    Preventive: { icon: Shield, bg: 'bg-emerald-50', border: 'border-emerald-200/70', text: 'text-emerald-700', badge: 'bg-emerald-100 text-emerald-700 border-emerald-200', iconColor: 'text-emerald-600', dot: 'bg-emerald-500' },
  };

  return (
    <div className="bg-white rounded-2xl p-4 sm:p-5 border border-slate-200/80 shadow-2xs h-full flex flex-col">
      <div className="flex items-center justify-between pb-3 mb-3 border-b border-slate-100">
        <div>
          <h2 className="text-base font-bold text-slate-900 tracking-tight">Recommended Actions</h2>
          <p className="text-xs text-slate-500 mt-0.5">Top {actions.length} actions by business value, generated by AI</p>
        </div>
        {onViewAll && (
          <button onClick={onViewAll} className="text-xs font-semibold text-blue-600 hover:text-blue-700 cursor-pointer flex items-center gap-1">
            View All <ArrowRight className="w-3.5 h-3.5" />
          </button>
        )}
      </div>
      <div className="space-y-3 flex-1">
        {actions.map((action) => {
          const config = severityConfig[action.severity] || severityConfig.Preventive;
          const Icon = config.icon;
          return (
            <div key={action.id} className={`rounded-xl border ${config.border} ${config.bg} p-3.5 hover:shadow-sm transition-all cursor-pointer group`}>
              <div className="flex items-start gap-3">
                <div className={`w-8 h-8 rounded-lg flex items-center justify-center shrink-0 ${config.bg} border ${config.border}`}>
                  <Icon className={`w-4 h-4 ${config.iconColor}`} />
                </div>
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 mb-0.5">
                    <span className={`text-[10px] font-bold px-2 py-0.5 rounded-md border ${config.badge}`}>{action.severity}</span>
                    <span className="text-[10px] text-slate-500 font-medium">{action.subtitle}</span>
                  </div>
                  <h3 className="text-xs font-bold text-slate-900 group-hover:text-blue-700 transition-colors">{action.title}</h3>
                </div>
                <ChevronRight className="w-4 h-4 text-slate-300 group-hover:text-blue-600 group-hover:translate-x-0.5 transition-all shrink-0 mt-1" />
              </div>
              <div className="flex items-center gap-3 mt-2.5 pl-11">
                <span className={`text-[10px] font-semibold px-1.5 py-0.5 rounded ${action.impact === 'High' ? 'bg-red-100/60 text-red-600' : action.impact === 'Medium' ? 'bg-amber-100/60 text-amber-700' : 'bg-slate-100 text-slate-600'}`}>{action.impact}</span>
                <span className="text-[10px] text-slate-500">{action.customerImpact}</span>
                <span className="text-[10px] font-bold text-emerald-700">{action.savingsOrBenefit}</span>
                <span className="text-[10px] text-slate-400 flex items-center gap-0.5"><Clock className="w-3 h-3" /> {action.effort}</span>
              </div>
            </div>
          );
        })}
        {actions.length === 0 && <p className="text-xs text-slate-400 text-center py-4">Loading recommendations...</p>}
      </div>
    </div>
  );
}
